C++ time to solve:  -0.6578860282897949
BPP: [0.5]
C++ time to solve:  -0.6583206653594971
SHO: [0.5]
Stat time to build:  -7.152557373046875e-07
Stat time to solve:  -6.000791311264038
STAT: [0.5]
Clauses 10 took -7.377428293228149
C++ time to solve:  -0.6525702476501465
BPP: [0.5, 1.0]
C++ time to solve:  -0.6649847030639648
SHO: [0.5, 1.0]
Stat time to build:  -4.76837158203125e-07
Stat time to solve:  -6.147308826446533
STAT: [0.5, 1.0]
Clauses 10 took -15.003504514694214
Traceback (most recent call last):
  File "testStatistics.py", line 240, in <module>
    main()
  File "testStatistics.py", line 237, in main
    test3()
  File "testStatistics.py", line 155, in test3
    plt.plot(xAxis, BPPSATpi, c='blue')
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/pyplot.py", line 3019, in plot
    return gca().plot(
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 501, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1,) and (2,)
